import { Ticket } from './ticket.model';

export const DUMMY_TICKETS: Ticket[] = [
  {
    id: 1001,
    subject: 'Payment not processing for Order #5234',
    customer: 'Sarah Mitchell',
    customerEmail: 'sarah.mitchell@outlook.com',
    customerPhone: '+61 3 9876 5432',
    chanel: 'Email',
    category: 'Billing',
    tags: ['payment', 'urgent', 'melbourne'],
    priority: 'High',
    status: 'InProgress',
    impact: 'SingleUser',
    customerTier: 'VIP',
    assignedTeam: 'Finance Team - Docklands',
    assignee: 'James Chen',
    createdAt: '2026-04-07T09:30:00Z',
    lastUpdatedAt: '2026-04-08T14:45:00Z',
    dueAt: '2026-04-10T17:00:00Z',
  },
  {
    id: 1002,
    subject: 'Delivery address mismatch - delivery failed',
    customer: 'Michael O\'Brien',
    customerEmail: 'mobrrien@gmail.com',
    customerPhone: '+61 3 9654 3210',
    chanel: 'Phone',
    category: 'Shipping',
    tags: ['delivery', 'address', 'southyarra'],
    priority: 'High',
    status: 'Open',
    impact: 'SingleUser',
    customerTier: 'Regular',
    assignedTeam: 'Logistics - Southbank',
    assignee: 'Emma Rodriguez',
    createdAt: '2026-04-08T11:15:00Z',
    lastUpdatedAt: '2026-04-08T11:15:00Z',
    dueAt: '2026-04-09T17:00:00Z',
  },
  {
    id: 1003,
    subject: 'Technical issue with app login',
    customer: 'Jessica Wong',
    customerEmail: 'j.wong@techmail.com.au',
    customerPhone: '+61 3 9432 1098',
    chanel: 'Chat',
    category: 'Technical Support',
    tags: ['app', 'login', 'bug', 'melbourne'],
    priority: 'Critical',
    status: 'InProgress',
    impact: 'MultipleUsers',
    customerTier: 'VIP',
    assignedTeam: 'Tech Support - Fitzroy',
    assignee: 'David Patel',
    createdAt: '2026-04-08T08:00:00Z',
    lastUpdatedAt: '2026-04-08T16:20:00Z',
    dueAt: '2026-04-08T18:00:00Z',
  },
  {
    id: 1004,
    subject: 'Refund request - defective product',
    customer: 'Robert Thompson',
    customerEmail: 'rthompson88@yahoo.com.au',
    customerPhone: '+61 3 9567 8901',
    chanel: 'Email',
    category: 'Returns & Refunds',
    tags: ['refund', 'defective', 'bayside'],
    priority: 'Medium',
    status: 'WaitingForCustomer',
    impact: 'SingleUser',
    customerTier: 'Regular',
    assignedTeam: 'Returns Team - Clayton',
    assignee: 'Lisa Anderson',
    createdAt: '2026-04-05T13:45:00Z',
    lastUpdatedAt: '2026-04-07T10:30:00Z',
    dueAt: '2026-04-12T17:00:00Z',
  },
  {
    id: 1005,
    subject: 'Account locked - security concern',
    customer: 'Amanda Foster',
    customerEmail: 'a.foster@corporate.com.au',
    customerPhone: '+61 3 9321 5678',
    chanel: 'Phone',
    category: 'Account Management',
    tags: ['security', 'locked', 'urgent', 'cbd'],
    priority: 'Critical',
    status: 'InProgress',
    impact: 'SingleUser',
    customerTier: 'VIP',
    assignedTeam: 'Security Team - Collingwood',
    assignee: 'Marcus Johnson',
    createdAt: '2026-04-08T15:30:00Z',
    lastUpdatedAt: '2026-04-08T16:10:00Z',
    dueAt: '2026-04-08T17:30:00Z',
  },
  {
    id: 1006,
    subject: 'Bulk order discount not applied',
    customer: 'Westside Trading Pty Ltd',
    customerEmail: 'accounts@westsidetrading.com.au',
    customerPhone: '+61 3 9876 4321',
    chanel: 'Email',
    category: 'Pricing',
    tags: ['bulk', 'discount', 'corporate', 'footscray'],
    priority: 'Medium',
    status: 'Open',
    impact: 'SingleUser',
    customerTier: 'VIP',
    assignedTeam: 'Sales Support - Collingwood',
    assignee: 'Nicole Gray',
    createdAt: '2026-04-07T10:00:00Z',
    lastUpdatedAt: '2026-04-07T10:00:00Z',
    dueAt: '2026-04-11T17:00:00Z',
  },
  {
    id: 1007,
    subject: 'Missing items from shipment',
    customer: 'Christopher Lewis',
    customerEmail: 'c.lewis@email.com.au',
    customerPhone: '+61 3 9543 2109',
    chanel: 'Chat',
    category: 'Shipping',
    tags: ['missing-items', 'shipment', 'melbourne'],
    priority: 'High',
    status: 'Resolved',
    impact: 'SingleUser',
    customerTier: 'Regular',
    assignedTeam: 'Warehouse - Truganina',
    assignee: 'Sofia Martinez',
    createdAt: '2026-04-06T14:20:00Z',
    lastUpdatedAt: '2026-04-08T09:15:00Z',
    dueAt: '2026-04-10T17:00:00Z',
  },
  {
    id: 1008,
    subject: 'Website crashing during checkout',
    customer: 'Victoria Park Property Group',
    customerEmail: 'support@vpropgroup.com.au',
    customerPhone: '+61 3 9765 4321',
    chanel: 'Chat',
    category: 'Technical Support',
    tags: ['website', 'crash', 'checkout', 'urgent', 'eastmebourne'],
    priority: 'Critical',
    status: 'Closed',
    impact: 'AllUsers',
    customerTier: 'VIP',
    assignedTeam: 'Infrastructure - Melbourne CBD',
    assignee: 'Alexander Kim',
    createdAt: '2026-04-08T12:00:00Z',
    lastUpdatedAt: '2026-04-08T15:45:00Z',
    dueAt: '2026-04-08T16:00:00Z',
  },
  {
    id: 1009,
    subject: 'Subscription renewal issue',
    customer: 'Patricia Green',
    customerEmail: 'pgreen@subscription.com.au',
    customerPhone: '+61 3 9234 5678',
    chanel: 'Email',
    category: 'Subscriptions',
    tags: ['subscription', 'renewal', 'billing', 'brighton'],
    priority: 'Medium',
    status: 'InProgress',
    impact: 'SingleUser',
    customerTier: 'Regular',
    assignedTeam: 'Billing - Docklands',
    assignee: 'Henry Cooper',
    createdAt: '2026-04-04T16:30:00Z',
    lastUpdatedAt: '2026-04-08T13:25:00Z',
    dueAt: '2026-04-11T17:00:00Z',
  },
  {
    id: 1010,
    subject: 'Feature request - add dark mode',
    customer: 'Nathan Clarke',
    customerEmail: 'n.clarke@design.com.au',
    customerPhone: '+61 3 9654 7890',
    chanel: 'WhatsApp',
    category: 'Feature Request',
    tags: ['feature', 'ui', 'dark-mode', 'melbourne'],
    priority: 'Low',
    status: 'Open',
    impact: 'SingleUser',
    customerTier: 'Regular',
    assignedTeam: 'Product Team - Fitzroy',
    assignee: 'Olivia Bennett',
    createdAt: '2026-04-02T11:45:00Z',
    lastUpdatedAt: '2026-04-02T11:45:00Z',
    dueAt: '2026-04-30T17:00:00Z',
  },
];
