import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { InputRuleDirective } from '../directives/input-rule';
import { RequiredErrorDirective } from '../directives/required-error';
import { CedulaEcuatorianaValidatorDirective } from '../directives/input-cedula';
type KycStatus = 'NotSubmitted' | 'Pending' | 'Verified' | 'Rejected';
interface KycApplication {
  id: number;
  fullName: string;
  mobile: string;
  pan: string;
  email: string;
  cedula: string;
  status: KycStatus;
}

@Component({
  selector: 'app-custom-components',
  imports: [FormsModule, InputRuleDirective, RequiredErrorDirective],
  templateUrl: './custom-components.html',
})
export class CustomComponents {
  // FORM MODEL (Template-driven form values)
  // These are bound to the input fields using [(ngModel)].
  // They always contain the latest values typed by the user.
  fullName = '';
  mobile = '';
  pan = '';
  cedula = '';
  email = '';
  // UI STATE (Controls when validation errors are shown)
  // We keep it false initially so the form looks clean on first load.
  // We set it true only when user clicks Submit.
  // Template uses this to show:
  // - validation messages
  // - RequiredErrorDirective styling
  isSubmitted = false;
  // IN-MEMORY STORAGE (Demo Purpose)
  // In real applications, IDs are generated by the backend database.
  // Here we simulate that using an auto-increment variable.
  private nextId = 1001;
  // Stores all submitted applications in memory.
  // This list is shown in the dashboard on the right side.
  applications: KycApplication[] = [];
  // VALIDATION GETTERS (Readable + reusable rules)
  // These getters keep the submit() method simple.
  // Also, the template can directly use these flags for UI messages.
  // Full Name must not be empty
  get isFullNameInvalid(): boolean {
    // trim() removes leading/trailing spaces so "   " is treated as empty
    return this.fullName.trim().length === 0;
  }
  // Mobile must be exactly 10 digits
  // Note: InputRuleDirective (digits rule) already removes non-digits.
  get isMobileInvalid(): boolean {
    return this.mobile.trim().length !== 10;
  }
  // PAN must be exactly 10 characters
  // Note: InputRuleDirective (uppercase rule) already converts to uppercase.
  get isPanInvalid(): boolean {
    return this.pan.trim().length !== 10;
  }
  // Basic email format validation
  // This checks: something@something.something
  get isEmailInvalid(): boolean {
    return !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(this.email.trim());
  }
  //cedula format validation

  get isCedulaValid(): boolean {
    let cedula = this.cedula.trim();
    if (!/^\d{10}$/.test(cedula)) return false;

    const provincia = parseInt(cedula.substring(0, 2), 10);
    if (provincia < 1 || provincia > 24) return false;

    const tercerDigito = parseInt(cedula[2], 10);
    if (tercerDigito >= 6) return false;

    const coeficientes = [2, 1, 2, 1, 2, 1, 2, 1, 2];
    let suma = 0;

    for (let i = 0; i < coeficientes.length; i++) {
      let valor = parseInt(cedula[i], 10) * coeficientes[i];
      if (valor >= 10) valor -= 9;
      suma += valor;
    }

    const digitoVerificador = parseInt(cedula[9], 10);
    const decenaSuperior = Math.ceil(suma / 10) * 10;
    const resultado = decenaSuperior - suma;

    const digitoCalculado = resultado === 10 ? 0 : resultado;

    return digitoCalculado === digitoVerificador;
  }
  // Single “master” check for overall form validity
  // If any field fails, the form is invalid.
  get isFormInvalid(): boolean {
    return (
      this.isFullNameInvalid || this.isMobileInvalid || this.isPanInvalid || this.isEmailInvalid || !this.isCedulaValid
    );
  }
  // SUBMIT HANDLER
  submit(): void {
    // Step 1: Mark as submitted
    // This activates required-field styling + validation messages in the UI.
    this.isSubmitted = true;
    // Step 2: Stop if validation fails
    // We don't store anything until the form is valid.
    if (this.isFormInvalid) return;
    // Step 3: Build the record that will be shown in the dashboard list
    // trim() ensures stored values are clean and consistent.
    const newApp: KycApplication = {
      id: this.nextId++, // simulate auto-generated unique ID
      fullName: this.fullName.trim(), // clean full name
      mobile: this.mobile.trim(), // clean mobile
      pan: this.pan.trim(), // clean PAN
      email: this.email.trim(), // clean email
      cedula: this.cedula.trim(), // clean CEDULA
      status: 'Pending', // default status for newly created record
    };
    // Step 4: Add the latest record at the TOP of the list
    // This is common in dashboards (most recent entry first).
    this.applications = [newApp, ...this.applications];
    // Step 5: Reset fields for next entry
    // Makes the form ready for a new submission.
    this.fullName = '';
    this.mobile = '';
    this.pan = '';
    this.email = '';
    this.cedula = '';
    // Step 6: Reset submission state
    // This removes validation UI and makes the next form entry clean.
    this.isSubmitted = false;
  }
  // RESET HANDLER
  reset(): void {
    // Clear all input fields
    this.fullName = '';
    this.mobile = '';
    this.pan = '';
    this.email = '';
    this.cedula = '';

    // Reset validation UI state (hide errors / remove red highlight)
    this.isSubmitted = false;
  }
}
